# Generated by Django 5.2.4 on 2025-07-18 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='experience_years',
        ),
        migrations.AlterUniqueTogether(
            name='result',
            unique_together={('student', 'course')},
        ),
    ]
